- id: lint-checks
  name: lint-checks
  description: Checks for ReLint violations in Julia code base
  language: script
  entry: ./scripts/run_julia_lint.sh
  types: [file]

- id: unsafe-log-checks
  args: [--rule LogStatementsMustBeSafe]
  name: unsafe-log-checks
  description: Checks for unsafe logs in Julia code base
  language: script
  entry: ./scripts/run_julia_lint.sh
  types: [file]
